openapi: 3.0.0
info:
  title: HR Management System API
  version: 1.0.0
  description: 人事労務管理システムのAPI仕様

servers:
  - url: http://localhost:3000/api
    description: ローカル開発環境

paths:
  /auth/login:
    post:
      summary: ログイン
      description: メールアドレスとパスワードでログイン認証を行う
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: password123
                rememberMe:
                  type: boolean
                  default: false
      responses:
        "200":
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: ログインに成功しました
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
        "401":
          description: 認証情報が無効
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: メールアドレスまたはパスワードが正しくありません
        "423":
          description: アカウントがロックされている
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: アカウントがロックされています

components:
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
